## global.R ##
library(data.table)
library(shiny)
library(dplyr)
library(ggplot2)
library(plotly)
library(markdown)
library(leaflet)
library(shinydashboard)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(wesanderson)
library(ggthemes)
library(gridExtra)
#setwd("C:/Users/samuelmao/Desktop/DataScience/Project1/Project1")
#read data into global.R
ks18<-fread(file = "./ks18.csv",sep = ',',fill=TRUE)
bycountry<-fread(file="./bycountry.csv")
